### ISSUE TITLE
https://boatboat.deconst.horse/ Container native tools

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#243]
Let's start with, or include a verb (and don't forget oxford comma).  How about:

Enjoy instant access to the Docker™ toolchain you already know and work with, including portability across providers, form-factors, and container orchestration environments.

**Comment by lauracly** [comment]
Changed final to: 
Instant access to the Docker™ toolchain that offers portability across providers, form-factors and container orchestration environments.

Standardized on direct, active descriptions. The other two categories start with Built for speed and Accelerated. Removed the "you already know and work with" because that seemed a bit redundant - its the official toolchain.  Thanks for the feedback.
