### ISSUE TITLE
Tutorial:  Docker swarm carina - wording question

### ISSUE THREAD

**Issue by catlook** [rackerlabs/docs-container-service#345]
Article: https://getcarina.com/docs/tutorials/docker-swarm-carina/

what does this mean: Whitelists expected mount calls for the container file system?

should it be"whitelists excepted mount calls"?

If so, I think you need a hyphen: Whitelists-excepted mount calls for the container file system

@jamiehannaford

**Comment by kmsholcomb** [comment]
"whitelists" is a verb here, and "expected" modifies "mount calls." If "expected" is the correct term here, then I think we are OK. And I think it is, because you can add the calls that you expect to get to a whitelist to ensure that they are allowed. I'm gonna close, but Jamie can comment if he has any input (and change the wording if needed).
